# This will be deployed and run inside a TEE with cryptographic attestation.

services:
    openrank-challenger:
        image: saucelord/randomness-beacon@sha256:0599e3945599595125cc594274e1892255ce6ded4b3e7e402128c3855e27e44c
        environment:
            # Set your mnemonic here or use secrets management
            - MNEMONIC=${MNEMONIC}
            - OPENRANK_MANAGER_ADDRESS=${OPENRANK_MANAGER_ADDRESS}
            - RPC_URL=https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}
        restart: unless-stopped
