[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
cache_path = "contracts/cache"
libs = ["contracts/lib"]
fs_permissions = [
    { access = "read-write", path = "./" },
    { access = "read-write", path = "./contracts" },
]
solc = "0.8.27"
# The following are needed for OpenZeppelin Upgrades:
# https://docs.openzeppelin.com/upgrades-plugins/foundry-upgrades#before_running
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@openzeppelin/contracts/=contracts/lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable/=contracts/lib/openzeppelin-contracts-upgradeable/contracts",
    "@openzeppelin-foundry-upgrades/=contracts/lib/openzeppelin-foundry-upgrades/src",
    "eigenlayer-middleware/=contracts/lib/eigenlayer-middleware/",
    "forge-std/=contracts/lib/openzeppelin-foundry-upgrades/lib/forge-std/src",
]

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
